### ISSUE TITLE
Feedback on Requirements 

### ISSUE THREAD

**Issue by marinamasterschool** [EdinaAdzem/QualityAssurance_SDLC_Automation#1]
Very well done. It appears that you have done more then the assignment was asking for. 

Assignment was to write the requirements for new features: 
1. Product Rating System
2.Age Verification for Alcoholic Products
3. Shipping Cost Changes

But it seems in this case requirements are written for the functionalities. 

Keep it as it is, and may be have a look at the requirements assignment and solution to see what was it for the new features.

**Comment by EdinaAdzem** [comment]
Added the remaining requirements. Thnx for the Input!
