### ISSUE TITLE
Feedback on Test Reporting and Bug Reports

### ISSUE THREAD

**Issue by PBauer256** [EdinaAdzem/QualityAssurance_SDLC_Automation#3]
I love the Format you used for the Bug Reports. Those are very detailed and easy to understand. Great job !

I also like the way you designed the test cases. It is very structured and clear.

Some small comments:

- The comments in your "Actual Result" section are not immediately clear. You would benefit from a simple FAIL/PASS Column. Specially in the overview. You have such great bug reports, you can describe any issues in detail there.
- For Test Case descriptions, you dont need the Actual Result / Pass/Fail columns.
- For the Reporting overview you kept the section "Boundary Testing". You could have tested many features using BVA, so its unclear what testcases can be found in that section. This is not very problematic here, but if you are naming Automation Tests / Automation Test Structure, the section names become important for finding results, generating reports, targetting classes to run in regression suits etc.

**Comment by EdinaAdzem** [comment]
Restructured and updated.  added suggested columns.  Many thanx for the feedback.
