### ISSUE TITLE
Feedback on Environment Setup

### ISSUE THREAD

**Issue by PBauer256** [EdinaAdzem/QualityAssurance_SDLC_Automation#4]
Lots of great Information there but, not much about "environment Infrastructure". Not sure there is a very good description of it in the course, but feel free to come up with information if you are missing it in the assignment.

Some Comments:
- You could add : Section about architecture, servers & their addresses. e.g. Webserver, DB-Server/Service, Admin Auth/Security information, Any Infrastructure in AWS? Cost/Maintenance of infrastructure ? Which Dependencies are on which server ? Small diagramm for CI/CD or deployment steps etc.
- For your Software Requirements its not clear what those requirements refer to. To run the server, Test it, be a user, or a dev ? 
- Same for your tools section, what are those tools used for ?

**Comment by EdinaAdzem** [comment]
Thnx for the feedback.  I restructured and added as per suggestions.
